# Server Configuration
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://ritvij:rit123@cluster0.plgjrb8.mongodb.net/
spring.data.mongodb.database=hospital_app

# Logging
logging.level.org.springframework.data.mongodb.core=DEBUG
